;; UI
(menu-bar-mode -1)
(tool-bar-mode -1)
(scroll-bar-mode -1)
(setq inhibit-startup-screen t)
(global-display-line-numbers-mode 1)
(load-theme 'modus-vivendi t)
(evil-mode 1)
(set-face-attribute 'default nil :height 140)
(show-paren-mode 1)
(global-hl-line-mode 1)
(global-visual-line-mode 1)
(require 'navigation)
(require 'ai)
(require 'project-ai)
(provide 'config)
